apiVersion: dev.kubi.zone/v1alpha1
kind: Zone
metadata:
  name: kubi-zone-cf-example
  namespace: kubizone
spec:
  delegations:
    - namespaces: []
      records:
        - pattern: "*"
          types: []
      zones: []
  domainName: kubi.zone.
  expire: 3600000
  negativeResponseCache: 360
  refresh: 86400
  retry: 7200
  ttl: 360
