---
apiVersion: dev.kubi.zone/v1alpha1
kind: Zone
metadata:
  name: kubi-zone-cf-example
  namespace: kubizone
spec:
  delegations:
    - records:
        - pattern: "*"
  domainName: kubi.zone.
  expire: 3600000
  negativeResponseCache: 360
  refresh: 86400
  retry: 7200
  ttl: 360
---
apiVersion: dev.kubi.zone/v1alpha1
kind: Record
metadata:
  name: cf-test-kubi-zone
spec:
  domainName: cf-test.kubi.zone.
  type: A
  rdata: "127.0.0.1"
